name: CI

on:
  pull_request:
    branches:
      - "*"

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        id: go

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.32.1/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install krew
        run: |
          cd "$(mktemp -d)"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.1/krew.tar.gz"
          tar zxvf krew.tar.gz
          KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64"
          chmod +x "$KREW"
          sudo mv "$KREW" /usr/local/bin/kubectl-krew
          kubectl krew version

      - name: Install validate-krew-manifest
        run: |
          export GOBIN=/usr/local/bin
          go install sigs.k8s.io/krew/cmd/validate-krew-manifest@latest
          validate-krew-manifest -h

      - uses: actions/checkout@v4

      - name: Run checks
        run: |
          make ci
