name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Install validate-krew-manifest
        run: |
          export GOPATH=$(go env GOPATH)
          export GOBIN=$GOPATH/bin
          mkdir -p $GOBIN
          go get sigs.k8s.io/krew/cmd/validate-krew-manifest
          sudo mv $GOBIN/* /usr/local/bin
          validate-krew-manifest -h

      - uses: actions/checkout@v1

      - name: Run checks
        run: |
          make ci
