name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install krew
        run: |
          cd "$(mktemp -d)"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.1/krew.tar.gz"
          tar zxvf krew.tar.gz
          KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64"
          chmod +x "$KREW"
          sudo mv "$KREW" /usr/local/bin/kubectl-krew
          kubectl krew version

      - name: Install validate-krew-manifest
        run: |
          export GOPATH=$(go env GOPATH)
          export GOBIN=$GOPATH/bin
          mkdir -p $GOBIN
          GO111MODULE=on go get sigs.k8s.io/krew/cmd/validate-krew-manifest
          sudo mv $GOBIN/* /usr/local/bin
          validate-krew-manifest -h

      - uses: actions/checkout@v1

      - name: Run checks
        run: |
          make ci
